import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { digitalImplementationArchitecture } from "../src/generated/digitalImplementationArchitecture.js";
import { architectureExplorerProjection } from "../src/components/framework/architectureExplorerProjection.js";

const model = await readFile(new URL("../src/architecture/digital-implementation/model.c4", import.meta.url), "utf8");
const generated = await readFile(new URL("../src/generated/digitalImplementationArchitecture.js", import.meta.url), "utf8");
const projectionSource = await readFile(new URL("../src/components/framework/architectureExplorerProjection.js", import.meta.url), "utf8");

const overlap = (aStart, aEnd, bStart, bEnd) => Math.min(aEnd, bEnd) - Math.max(aStart, bStart);

function segmentOverlapsBorder([ax, ay], [bx, by], [cx, cy], [dx, dy]) {
  const horizontalA = ay === by;
  const horizontalB = cy === dy;
  if (horizontalA !== horizontalB) return false;
  if (horizontalA && ay === cy) return overlap(ax, bx, cx, dx) > 1;
  if (!horizontalA && ax === cx) return overlap(ay, by, cy, dy) > 1;
  return false;
}

function rectangleBorders([x, y, width, height]) {
  return [
    [[x, y], [x + width, y]], [[x + width, y], [x + width, y + height]],
    [[x + width, y + height], [x, y + height]], [[x, y + height], [x, y]],
  ];
}

function pointOnBoundary([x, y], [left, top, width, height]) {
  const right = left + width;
  const bottom = top + height;
  return ((x === left || x === right) && y >= top && y <= bottom)
    || ((y === top || y === bottom) && x >= left && x <= right);
}

function rectanglesOverlap(a, b) {
  return (
    a.x < b.x + b.width
    && a.x + a.width > b.x
    && a.y < b.y + b.height
    && a.y + a.height > b.y
  );
}

test("LikeC4 is the single semantic source for the generated digital architecture", () => {
  assert.equal(digitalImplementationArchitecture.id, "digital-implementation");
  assert.equal(digitalImplementationArchitecture.nodes.length, 9);
  assert.equal(digitalImplementationArchitecture.edges.length, 13);
  assert.equal(new Set(digitalImplementationArchitecture.nodes.map((node) => node.id)).size, 9);
  assert.equal(new Set(digitalImplementationArchitecture.edges.map((edge) => edge.id)).size, 13);
  for (const edge of digitalImplementationArchitecture.edges) {
    assert.ok(digitalImplementationArchitecture.nodes.some((node) => node.id === edge.from));
    assert.ok(digitalImplementationArchitecture.nodes.some((node) => node.id === edge.to));
  }
  assert.match(model, /specification \{/);
  assert.match(generated, /Generated by scripts\/generate-digital-architecture\.mjs/);
});

test("each projection covers the same node and relationship identifiers exactly once", () => {
  const nodeIds = new Set(digitalImplementationArchitecture.nodes.map((node) => node.id));
  const edgeIds = new Set(digitalImplementationArchitecture.edges.map((edge) => edge.id));
  for (const layout of Object.values(architectureExplorerProjection)) {
    assert.deepEqual(new Set(Object.keys(layout.nodes)), nodeIds);
    assert.deepEqual(new Set(Object.keys(layout.routes)), edgeIds);
    for (const edge of digitalImplementationArchitecture.edges) {
      const route = layout.routes[edge.id];
      assert.ok(route.points.length >= 2, `${edge.id} needs a route`);
      const source = layout.nodes[edge.from];
      const target = layout.nodes[edge.to];
      const first = route.points[0];
      const last = route.points.at(-1);
      assert.ok(pointOnBoundary(first, source), `${edge.id} must start on its source`);
      assert.ok(pointOnBoundary(last, target), `${edge.id} must end on its target`);
    }
  }
});

test("routes do not run along unrelated node borders or layer dividers", () => {
  for (const layout of Object.values(architectureExplorerProjection)) {
    const borders = Object.entries(layout.nodes).flatMap(([id, box]) => rectangleBorders(box).map((segment) => ({ id, segment })));
    const dividers = Object.entries(layout.layers).flatMap(([id, box]) => rectangleBorders(box).map((segment) => ({ id: `layer:${id}`, segment })));
    for (const edge of digitalImplementationArchitecture.edges) {
      const route = layout.routes[edge.id];
      for (let index = 1; index < route.points.length; index += 1) {
        const segment = [route.points[index - 1], route.points[index]];
        for (const border of [...borders, ...dividers]) {
          if (border.id === edge.from || border.id === edge.to) continue;
          assert.equal(segmentOverlapsBorder(segment[0], segment[1], border.segment[0], border.segment[1]), false, `${edge.id} overlaps ${border.id}`);
        }
      }
    }
  }
});

test("mobile relationship labels stay clear of nodes, one another, and layer titles", () => {
  const layout = architectureExplorerProjection.mobile;
  const labels = digitalImplementationArchitecture.edges.map((edge) => {
    const [x, y] = layout.routes[edge.id].label;
    const width = Math.max(34, edge.label.length * 17 + 8);
    return { id: edge.id, x: x - width / 2, y: y - 12, width, height: 24 };
  });
  const layerTitles = Object.entries(layout.layers).map(([layerId, [x, y]]) => {
    const title = digitalImplementationArchitecture.nodes.find((node) => node.layer === layerId)?.layerLabel ?? "";
    return { id: layerId, x: x + 30, y: y + 13, width: title.length * 24, height: 30 };
  });
  for (const label of labels) {
    for (const node of Object.values(layout.nodes)) {
      const [x, y, width, height] = node;
      assert.equal(rectanglesOverlap(label, { x, y, width, height }), false, `${label.id} overlaps a mobile node`);
    }
    for (const title of layerTitles) assert.equal(rectanglesOverlap(label, title), false, `${label.id} overlaps layer title ${title.id}`);
  }
  for (const [index, label] of labels.entries()) {
    for (const other of labels.slice(index + 1)) assert.equal(rectanglesOverlap(label, other), false, `${label.id} overlaps ${other.id}`);
  }
});

test("projection contains geometry only, not duplicated architecture facts", () => {
  for (const forbidden of ["提出数字化需求", "协同设计", "企业业务架构", "数字事实与结果"]) {
    assert.doesNotMatch(projectionSource, new RegExp(forbidden));
  }
  assert.match(projectionSource, /Geometry-only projection/);
});
